---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: flux
  annotations:
    iam.gke.io/gcp-service-account: ops-flux@issho-ni.iam.gserviceaccount.com
  name: flux
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flux
  name: flux
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux
  labels:
    app.kubernetes.io/name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: default
  labels:
    app.kubernetes.io/name: flux
  annotations:
    flux.weave.works/tag.flux: semver:~1
    flux.weave.works/tag.prometheus-to-sd: semver:~0
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flux
      annotations:
        prometheus.io.port: "3031"
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      serviceAccountName: flux
      volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
            defaultMode: 0400
        - name: git-keygen
          emptyDir:
            medium: Memory
      containers:
        - name: flux
          image: fluxcd/flux:1.13.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: ISSHO_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: issho-cluster
                  key: ISSHO_CLUSTER
          ports:
            - name: flux
              containerPort: 3030
              protocol: TCP
            - name: prometheus
              containerPort: 3031
              protocol: TCP
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
              readOnly: true
            - name: git-keygen
              mountPath: /var/fluxd/keygen
          args:
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-url=git@github.com:issho-ni/infrastructure
            - --git-branch=master
            - --git-path=k8s/common,k8s/$(ISSHO_CLUSTER)
            - --listen-metrics=:3031
            - --log-format=json
        - name: prometheus-to-sd
          image: gcr.io/google-containers/prometheus-to-sd:v0.5.2
          ports:
            - name: profiler
              containerPort: 6060
          command:
            - /monitor
            - --stackdriver-prefix=custom.googleapis.com
            - --source=$(POD_NAME):http://localhost:3031/metrics
            - --pod-id=$(POD_NAME)
            - --namespace-id=$(POD_NAMESPACE)
            - --scrape-interval=5s
            - --export-interval=30s
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
  namespace: default
type: Opaque
