---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: flux
  annotations:
    iam.gke.io/gcp-service-account: ops-flux@issho-ni.iam.gserviceaccount.com
  name: flux
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flux
  name: flux
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux
  labels:
    app.kubernetes.io/name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: default
  labels:
    app.kubernetes.io/name: flux
  annotations:
    flux.weave.works/tag.flux: semver:~1
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flux
      annotations:
        prometheus.io.port: "3031"
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      serviceAccountName: flux
      volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
            defaultMode: 0400
        - name: git-keygen
          emptyDir:
            medium: Memory
      containers:
        - name: flux
          image: fluxcd/flux:1.13.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: ISSHO_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: issho-cluster
                  key: ISSHO_CLUSTER
          ports:
            - containerPort: 3030
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
              readOnly: true
            - name: git-keygen
              mountPath: /var/fluxd/keygen
          args:
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-url=git@github.com:issho-ni/infrastructure
            - --git-branch=master
            - --git-path=k8s/common,k8s/$(ISSHO_CLUSTER)
            - --listen-metrics=:3031
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
  namespace: default
type: Opaque
